language: java
before_install:
- openssl aes-256-cbc -K $encrypted_6b9b870d0f89_key -iv $encrypted_6b9b870d0f89_iv
  -in .travis/id_rsa.enc -out id_rsa -d

after_success:
- chmod ugo+x .travis/deploy.sh
- .travis/deploy.sh