language: java

branches:
  only:
    - master
    - dev

addons:
  ssh_known_hosts:
  - $IP

before_install:
- openssl aes-256-cbc -K $encrypted_6b9b870d0f89_key -iv $encrypted_6b9b870d0f89_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d

after_success:
- on:
     branch: master
  provider: script
  script:" .travis/deploy.sh"

- on:
     branch: dev
  provider: script
  script:" .travis/deploy.sh"

