language: java
services:
- mysql
- mysql -u root --password="" < travis.sql



before_install:
- openssl aes-256-cbc -K $encrypted_457cd3e97970_key -iv $encrypted_457cd3e97970_iv
  -in id_rsa.enc -out id_rsa -d

